name: Build and Release Theme

on:
  release:
    types: [created]

permissions:
  contents: write
  actions: read

jobs:
  build:
    name: Build and Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create theme directory structure
        run: |
          mkdir -p build/catalyst-digital

      - name: Copy theme files (excluding specified files/folders)
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='vendor' \
            --exclude='node_modules' \
            --exclude='.gitignore' \
            --exclude='composer.json' \
            --exclude='composer.lock' \
            --exclude='.DS_Store' \
            --exclude='build' \
            ./ build/catalyst-digital/

      - name: Create zip archive
        run: |
          cd build
          zip -r catalyst-digital.zip catalyst-digital

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./build/catalyst-digital.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
